AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 50
    MemorySize: 5000
    Environment:
      Variables:
        API_ID: "dummy_api_id"
        AFFIRIATE_ID: "dummy_affiriate_id"
        DMM_API_BASE_URL: "dummy_dmm_api_base_url"
  Api:
    BinaryMediaTypes:
      - image/png
      - image/jpg
      - image/jpeg

Resources:
  ImgRecommendFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /img-rec
            Method: post
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./img-recommend
      DockerTag: python3.7-v1

  InitActressesFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /init-actresses
            Method: get
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./init-actresses
      DockerTag: python3.7-v1

  ScoreRecommendFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /score-rec
            Method: post
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./score-recommend
      DockerTag: python3.7-v1
