AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 50
    MemorySize: 5000
  Api:
    BinaryMediaTypes:
      - image/png
      - image/jpg
      - image/jpeg

Resources:
  ImgRecommendFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /img-rec
            Method: post
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./img-recommend
      DockerTag: python3.7-v1

  InitActressesFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /init-actresses
            Method: get
      Environment:
        Variables:
          API_ID: dummy
          AFFIRIATE_ID: dummy
          DMM_API_BASE_URL: dummy

    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./init-actresses
      DockerTag: python3.7-v1

  ScoreRecommendFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /score-rec
            Method: post
      Environment:
        Variables:
          API_ID: 3bAvsFFabgmGGVWUTVTR
          AFFIRIATE_ID: souhub-990
          DMM_API_BASE_URL: https://api.dmm.com/affiliate/v3/ActressSearch
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./score-recommend
      DockerTag: python3.7-v1

  # S3TestBucket2:
  #   Type: AWS::S3::Bucket
  #   Properties:
  #     BucketName: souhub-s3-test-function2
